### PR TITLE
[STMARKS-002] Add toggle button

### LINKED ISSUE #4: Add toggle button
- [ ] Button does not need to be interactive, ie it does not have to change the page colour, it just needs to be there

### PR DESCRIPTION
**Pull request by klam656**
Issue
Add a toggle button in the navigation bar.

Solution
Add a "<Switch>" in NavBar/index.tsx, "<Switch>" which in the MUI theme.  Also, I removed the navigation button - commit (b69dc52c8648c14e85bece85695ba262cef177da)

In order to run the build, I did modify some other files. - commit (1. ccae1fc969e2244dfe276a36a631ce2d8cd56f89, 2. e802993774c20cdc060c47b00cc862af2e5f8121, 3. 382b73ce93f7fa17a693e6b40f77300c2225d144, 4. 1f2690c237506f03b0e64fbdca463cf5b8a92251)

Risk
I don't think there is a risk. 

Reviewed by
Jason, Molina, and hopefully others

### CODE REVIEW

**Review by butterplup — COMMENTED** [review]
I'm not actually sure that we should be removing the `/map` navigation button altogether since it helps skip a step when on the directory or plot pages.

Also you should make sure to add a description to this PR following the Git guidelines that Jason mentioned in the last dev meeting :)

**Comment by klam656** [comment]
Thank you, Joel! I added a description, it was totally my fault haven't read the doc. 
I am not sure whether or not the map button is needed, if it is needed, then I will add it back. :>

**Review by jzha411 — APPROVED** [review]
Looks good

**Review by molinalim — COMMENTED** [review]
Well done, Kenny! 

I agree with Joel that we should keep the map button in the /directory page and only replace the map button in the /map page with the Switch. You could either fix this within this branch, or do it on your new task branch (styling). Thanks!

**Pull request merged**
